module.exports = Object.freeze({
  EQUAL_TO: "EQUAL_TO",
  NOT_EQUAL_TO: "NOT_EQUAL_TO",
  LESS_THAN: "LESS_THAN",
  LESS_THAN_OR_EQUAL_TO: "LESS_THAN_OR_EQUAL_TO",
  GREATER_THAN: "GREATER_THAN",
  GREATER_THAN_OR_EQUAL_TO: "GREATER_THAN_OR_EQUAL_TO",
  REGEXP: "REGEXP"
});
